version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # dependencies

      # locked to ^15.4.1, since newer majors include breaking changes that may impact us
      - dependency-name: "yargs"
