version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # dependencies

      # pinned to the most popular versions
      - dependency-name: "@azure/openapi-markdown"
      - dependency-name: "json-schema-traverse"

      # locked to "^6.12.6", for compat with our version of TypeScript
      - dependency-name: "ajv"

      # Locked to "^9.3.5", for compat with cjs
      - dependency-name: "glob"

      # locked to "^5.1.1", since newer majors include breaking changes that impact us
      - dependency-name: "inversify"

      # locked to "^6.3.0", since newer majors remove features we depend on
      - dependency-name: "path-to-regexp"

      # locked to ~3.16.0, since newer minors include an undocumented breaking change in typings that impacts us
      # https://github.com/winstonjs/winston/issues/2528
      - dependency-name: "winston"

      # locked to ^15.4.1, since newer majors include breaking changes that may impact us
      - dependency-name: "yargs"

      # devDependencies

      # locked to 4.14.182, for compat with our version of TypeScript
      - dependency-name: "@types/lodash"

      # locked to "^15.6.1", for compat with our version of TypeScript
      - dependency-name: "@types/node"

      # locked for compat with each other
      - dependency-name: "@typescript-eslint/eslint-plugin"
      - dependency-name: "@typescript-eslint/parser"
      - dependency-name: "eslint"
      - dependency-name: "eslint-config-prettier"
      - dependency-name: "eslint-plugin-prettier"

      # locked to "^26" for compat with each other
      - dependency-name: "@types/jest"
      - dependency-name: "jest"
      - dependency-name: "ts-jest"

      # locked to 2.8.8, for compat with our version of TypeScript
      - dependency-name: "prettier"

      # locked to "~4.3.5", for compat with our TS code
      - dependency-name: "typescript"

      # overrides

      # pinned to 1.7.2, for compat with our version of TypeScript
      - dependency-name: "@azure/core-auth"

      # pinned to 1.7.0, for compat with our version of TypeScript
      - dependency-name: "@azure/core-util"

      # locked to ~2.6.1, since newer minors include an undocumented breaking change in typings that impacts us
      # https://github.com/winstonjs/logform/issues/336
      - dependency-name: "logform"
