version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Pinned to the most popular versions
      - dependency-name: "openapi-markdown"
      - dependency-name: "json-schema-traverse"
      - dependency-name: "reflect-metadata"
