pool:
  vmImage: "Ubuntu 16.04"

trigger:
  - master

- checkout: self
  submodules: true

steps:
  - task: Npm@1
    displayName: "npm install"
    inputs:
      verbose: false

  - task: Npm@1
    displayName: "npm run slow-test"
    inputs:
      command: custom
      verbose: false
      customCommand: run slow-test

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/test-results.xml"
      testRunTitle: "Test results for JavaScript"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
