trigger:
  branches:
    include:
    - develop
    - hotfix/*
    - release/*

pr:
  branches:
    include:
    - develop
    - feature/*
    - hotfix/*
    - release/*

extends:
  template: /eng/templates/stages/oav.yml