trigger:
  branches:
    include:
    - develop
    - hotfix/*
    - release/*
  paths:
    include:
    - /

pr:
  branches:
    include:
    - develop
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - /

extends:
  template: /eng/templates/stages/oav.yml