# TODO: refactor the hilariously common jobs

parameters:
  - name: BeforeVersion
    type: string
    default: ''
  - name: AfterVersion
    type: string
    default: 'LOCAL' #specialcase value that will install the local version of oav

pool:
  name: azsdk-pool-mms-ubuntu-2004-general
  vmImage: MMSUbuntu20.04

jobs:
  - job: RegressionASpecs
    variables:
      - name: OutputFolder
        value: $(Build.ArtifactStagingDirectory)/${{ parameters.BeforeVersion }}
      - name: RestSpecsRepo
        value: $(Build.ArtifactStagingDirectory)/azure-rest-api-specs
    timeoutInMinutes: 360
    displayName: Run ${{ parameters.BeforeVersion }} Specs
    steps:
      - template: ./regression-steps.yml
        parameters:
          TargetVersion: ${{ parameters.BeforeVersion }}
          Type: "validate-spec"

  - job: RegressionAExamples
    variables:
      - name: OutputFolder
        value: $(Build.ArtifactStagingDirectory)/${{ parameters.BeforeVersion }}
      - name: RestSpecsRepo
        value: $(Build.ArtifactStagingDirectory)/azure-rest-api-specs
    timeoutInMinutes: 360
    displayName: Run ${{ parameters.BeforeVersion }} Examples
    steps:
      - template: ./regression-steps.yml
        parameters:
          TargetVersion: ${{ parameters.BeforeVersion }}
          Type: "validate-example"

  - job: RegressionBSpecs
    variables:
      - name: OutputFolder
        value: $(Build.ArtifactStagingDirectory)/${{ parameters.AfterVersion }}
      - name: RestSpecsRepo
        value: $(Build.ArtifactStagingDirectory)/azure-rest-api-specs
    timeoutInMinutes: 360
    displayName: Run ${{ parameters.AfterVersion }} Specs
    steps:
      - template: ./regression-steps.yml
        parameters:
          TargetVersion: ${{ parameters.AfterVersion }}
          Type: "validate-spec"

  - job: RegressionBExamples
    variables:
      - name: OutputFolder
        value: $(Build.ArtifactStagingDirectory)/${{ parameters.AfterVersion }}
      - name: RestSpecsRepo
        value: $(Build.ArtifactStagingDirectory)/azure-rest-api-specs
    timeoutInMinutes: 360
    displayName: Run ${{ parameters.AfterVersion }} Examples
    steps:
      - template: ./regression-steps.yml
        parameters:
          TargetVersion: ${{ parameters.AfterVersion }}
          Type: "validate-example"

  - job: Summarize
    timeoutInMinutes: 180
    dependsOn: 
      - RegressionASpecs
      - RegressionBSpecs
      - RegressionAExamples
      - RegressionBExamples
    displayName: Run Diff

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: "${{ parameters.BeforeVersion }}-validate-spec"
        targetPath: $(Build.ArtifactStagingDirectory)/before
        
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: "${{ parameters.BeforeVersion }}-validate-example"
        targetPath: $(Build.ArtifactStagingDirectory)/before

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: "${{ parameters.AfterVersion }}-validate-spec"
        targetPath: $(Build.ArtifactStagingDirectory)/after

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: "${{ parameters.AfterVersion }}-validate-example"
        targetPath: $(Build.ArtifactStagingDirectory)/after

    - bash: |
        ls -R $(Build.ArtifactStagingDirectory)
        diff -qr $(Build.ArtifactStagingDirectory)/before $(Build.ArtifactStagingDirectory)/after
      displayName: Dump Visible Artifacts