/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

export import LiveRequest = require('./liveRequest')
export import LiveResponse = require('./liveResponse')
export import RequestResponse = require('./requestResponse')
export import OperationInfo = require('./operationInfo')
export import LiveValidationError = require('./liveValidationError')
export import ErrorResponse = require('./errorResponse')
export import ErrorWrapper = require('./errorWrapper')
export import RequestValidationResult = require('./requestValidationResult')
export import ResponseValidationResult = require('./responseValidationResult')
export import ValidationResult = require('./validationResult')
export import PotentialOperationsResult = require('./potentialOperationsResult')
