import liveRequest = require('./liveRequest');
import liveResponse = require('./liveResponse');
import requestResponse = require('./requestResponse');
import operationInfo = require('./operationInfo');
import liveValidationError = require('./liveValidationError');
import errorResponse = require('./errorResponse');
import errorWrapper = require('./errorWrapper');
import requestValidationResult = require('./requestValidationResult');
import responseValidationResult = require('./responseValidationResult');
import validationResult = require('./validationResult');
import potentialOperationsResult = require('./potentialOperationsResult');
export declare const LiveRequest: typeof liveRequest;
export declare const LiveResponse: typeof liveResponse;
export declare const RequestResponse: typeof requestResponse;
export declare const OperationInfo: typeof operationInfo;
export declare const LiveValidationError: typeof liveValidationError;
export declare const ErrorResponse: typeof errorResponse;
export declare const ErrorWrapper: typeof errorWrapper;
export declare const RequestValidationResult: typeof requestValidationResult;
export declare const ResponseValidationResult: typeof responseValidationResult;
export declare const ValidationResult: typeof validationResult;
export declare const PotentialOperationsResult: typeof potentialOperationsResult;
