/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the ValidationResult class.
 * @constructor
 * Describes the validation result of the live request, response validation.
 *
 * @member {object} [requestValidationResult] Describes the validation result
 * of the live request.
 *
 * @member {boolean} [requestValidationResult.successfulRequest] Describes the
 * status of live request validation.
 *
 * @member {object} [requestValidationResult.operationInfo] The corresponding
 * operation in openapi spec that was used for validating the request.
 *
 * @member {string} [requestValidationResult.operationInfo.operationId] The id
 * of the operation against which validation happened. This will help find the
 * problematic information in the spec and will be useful in preparing report.
 *
 * @member {string} [requestValidationResult.operationInfo.apiVersion]
 * Describes the api-version of the openapi specification. This will help find
 * the openapi spec corresponding to that api-version and will be useful in
 * preparing report.
 *
 * @member {object} [requestValidationResult.errors] Provides more information
 * about live response validation.
 *
 * @member {object} [responseValidationResult] Describes the validation result
 * of the live response.
 *
 * @member {boolean} [responseValidationResult.successfulResponse] Describes
 * the status of live response validation.
 *
 * @member {object} [responseValidationResult.operationInfo] The corresponding
 * operation in openapi spec that was used for validating the response.
 *
 * @member {string} [responseValidationResult.operationInfo.operationId] The id
 * of the operation against which validation happened. This will help find the
 * problematic information in the spec and will be useful in preparing report.
 *
 * @member {string} [responseValidationResult.operationInfo.apiVersion]
 * Describes the api-version of the openapi specification. This will help find
 * the openapi spec corresponding to that api-version and will be useful in
 * preparing report.
 *
 * @member {object} [responseValidationResult.errors] Provides more information
 * about live response validation.
 *
 */
class ValidationResult {
  constructor() {
  }

  /**
   * Defines the metadata of ValidationResult
   *
   * @returns {object} metadata of ValidationResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ValidationResult',
      type: {
        name: 'Composite',
        className: 'ValidationResult',
        modelProperties: {
          requestValidationResult: {
            required: false,
            readOnly: true,
            serializedName: 'requestValidationResult',
            type: {
              name: 'Composite',
              className: 'RequestValidationResult'
            }
          },
          responseValidationResult: {
            required: false,
            readOnly: true,
            serializedName: 'responseValidationResult',
            type: {
              name: 'Composite',
              className: 'ResponseValidationResult'
            }
          }
        }
      }
    };
  }
}

module.exports = ValidationResult;
