export type Code =
  "INTERNAL_ERROR" |
  "INITIALIZATION_ERROR" |
  "RESOLVE_SPEC_ERROR" |
  "REF_NOTFOUND_ERROR" |
  "JSON_PARSING_ERROR" |
  "REQUIRED_PARAMETER_EXAMPLE_NOT_FOUND" |
  "ERROR_IN_PREPARING_REQUEST" |
  "X-MS-EXAMPLE_NOT_FOUND" |
  "RESPONSE_VALIDATION_ERROR" |
  "REQUEST_VALIDATION_ERROR" |
  "RESPONSE_BODY_VALIDATION_ERROR" |
  "RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE" |
  "RESPONSE_STATUS_CODE_NOT_IN_SPEC" |
  "RESPONSE_SCHEMA_NOT_IN_SPEC" |
  "REQUIRED_PARAMETER_NOT_IN_EXAMPLE_ERROR" |
  "BODY_PARAMETER_VALIDATION_ERROR" |
  "TYPE_VALIDATION_ERROR" |
  "CONSTRAINT_VALIDATION_ERROR" |
  "STATUS_CODE_NOT_IN_EXAMPLE_ERROR" |
  "SEMANTIC_VALIDATION_ERROR" |
  "MULTIPLE_OPERATIONS_FOUND" |
  "NO_OPERATION_FOUND" |
  "INCORRECT_INPUT" |
  "POTENTIAL_OPERATION_SEARCH_ERROR" |
  "PATH_NOT_FOUND_IN_REQUEST_URL" |
  "OPERATION_NOT_FOUND_IN_CACHE" |
  // Implies we found correct api-version + provider in cache
  "OPERATION_NOT_FOUND_IN_CACHE_WITH_VERB" |
  // Implies we found correct provider in cache
  "OPERATION_NOT_FOUND_IN_CACHE_WITH_API" |
  // Implies we never found correct provider in cache
  "OPERATION_NOT_FOUND_IN_CACHE_WITH_PROVIDER" |
  "DOUBLE_FORWARD_SLASHES_IN_URL" |
  "NO_DEFAULT_RESPONSE"

export const code = (c: Code) => c
