name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node 22
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: "npm"
          node-version: 22

      - name: Install deps
        run: |
          echo "::group::npm ci"
          npm ci
          echo "::endgroup::"
          echo "::group::npm ls -a"
          npm ls -a || true
          echo "::endgroup::"
        shell: bash

      # script "build" also calls "lint"
      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
